########################################################
# bootstrap Square bashrc; please don't change this bit.
########################################################
if [[ -f "$DOTTIE_HOME/bash/bashrc" ]]; then
  source $DOTTIE_HOME/bash/bashrc
fi
########################################################


###########################################
# Feel free to make your own changes below.
###########################################

# vim: filetype=sh
